"""Generate the complete REST schema; --check detects documentation drift."""

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import yaml  # noqa: E402

from services.semantic_middle_layer_api.app import app  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/api/semantic_middle_layer.openapi.yaml"
    payload = app.openapi()
    rendered = (
        "# Generated by python tools/export_openapi.py; do not edit manually.\n"
        + yaml.safe_dump(payload, allow_unicode=True, sort_keys=False)
    )
    if args.check:
        if not target.exists() or yaml.safe_load(target.read_text()) != payload:
            raise SystemExit("OpenAPI is stale: run python tools/export_openapi.py")
        print("OpenAPI matches the application routes and schemas")
    else:
        target.write_text(rendered, encoding="utf-8")
        print(f"Generated {len(payload['paths'])} API paths")


if __name__ == "__main__":
    main()
